import streamlit as st
import traceback
from agents.architect import ArchitectAgent
from agents.analyst import AnalystAgent
from agents.validator import ValidationAgent
from agents.bi import BIAgent

from config import (
    KPI_DIRECTORY_PATH,
    ARCHITECT_PROMPT_PATH,
    MODEL_NAME
)

st.set_page_config(page_title="L&T Executive AI Analyst", layout="wide")
st.title("🤖 L&T Executive AI Analyst")
st.subheader("Ask a business question")

@st.cache_resource
def load_agents():
    """Initializes agents and loads data into memory only once to prevent crashes."""
    try:
        return {
            "architect": ArchitectAgent(
                KPI_DIRECTORY_PATH,
                ARCHITECT_PROMPT_PATH,
                MODEL_NAME
            ),
            "analyst": AnalystAgent(),
            "validator": ValidationAgent(KPI_DIRECTORY_PATH),
            "bi": BIAgent(KPI_DIRECTORY_PATH)
        }
    except Exception as e:
        st.error(f"Initialization Failed: {e}")
        return None

agents = load_agents()

if agents:
    user_query = st.text_input("Enter your business question (e.g., 'What is the Margin % for June 2025?'):")

    if user_query:
        try:
            with st.spinner("Thinking..."):
                # 1. ARCHITECT: Identify KPI and Filters
                architecture = agents["architect"].run(user_query)

                if architecture["kpi_id"] is None:
                    st.warning("⚠️ Could not determine KPI. Try using terms like 'Margin', 'Revenue', or 'FTE'.")
                    st.stop()

                # 2. ANALYST: Run specialized SQL logic
                df = agents["analyst"].run(architecture)

                # 3. RESULTS & AUDIT TABS
                if df is not None and not df.empty:
                    tab_res, tab_audit = st.tabs(["📊 Results Dashboard", "🛠️ Technical Audit"])
                    
                    with tab_res:
                        # Render professional charts and KPI cards
                        agents["bi"].render(
                            architecture["kpi_id"], 
                            df, 
                            architecture.get("comparison")
                        )
                    
                    with tab_audit:
                        st.markdown("### 🔍 Calculation Traceability")
                        # Show the specific SQL query generated by the Analyst
                        st.code(agents["analyst"].last_sql, language="sql")
                        
                        # Show raw data for verification
                        st.write("**Raw Data Table:**")
                        st.dataframe(df)
                        
                        # Show architecture metadata
                        st.write("**KPI ID identified:**", architecture["kpi_id"])
                else:
                    st.error("The analyst returned no data for this query. Check if the dates or segments exist.")

        except Exception:
            st.error("The app encountered a processing error.")
            st.expander("Technical Traceback").code(traceback.format_exc())
