import streamlit as st
import pandas as pd
import duckdb
import os
import matplotlib.pyplot as plt
from langchain_openai import ChatOpenAI

# --- 1. DATA ENGINE (Preserved) ---
@st.cache_resource
def load_data():
    conn = duckdb.connect(database=':memory:')
    if os.path.exists("pnl_data.xlsx"):
        df_pnl = pd.read_excel("pnl_data.xlsx")
        df_pnl['Month'] = pd.to_datetime(df_pnl['Month'], errors='coerce')
        conn.register("pnl_data", df_pnl)
    if os.path.exists("ut_data.xlsx"):
        df_ut = pd.read_excel("ut_data.xlsx")
        df_ut['Date'] = pd.to_datetime(df_ut['Date'], errors='coerce')
        conn.register("ut_data", df_ut)
    return conn

conn = load_data()

# --- 2. THE ANALYST ENGINE (v13.0 with FTE Guard) ---
def execute_ai_query(user_query):
    llm = ChatOpenAI(model="gpt-4o", temperature=0)

    # 1. Intent Classification
    intent_prompt = f"Classify as 'DATA' or 'CHAT'. User: {user_query}. Output one word."
    intent = llm.invoke(intent_prompt).content.strip().upper()

    if 'CHAT' in intent:
        return "CHAT", None, llm.invoke(f"Greet as L&T Assistant: {user_query}").content

    # 2. SQL Path with Strict Definitions
    system_prompt = """
    You are a Financial SQL Generator. Return ONLY SQL for DuckDB.
    
    CRITICAL DEFINITIONS:
    - FTE / Headcount / PS Number: ALWAYS use 'COUNT(DISTINCT PSNo)'. Never use hours for this.
    - Utilization: ALWAYS use '(SUM(TotalBillableHours) / NULLIF(SUM(NetAvailableHours), 0)) * 100'.
    - Segment: Use 'ut_data.Segment' for headcount/utilization and 'pnl_data.Segment' for revenue/cost.
    
    TABLES:
    - pnl_data: [Month, FinalCustomerName, "Amount in USD", Type, Group1, Group3, Segment]
    - ut_data: [Date, FinalCustomerName, PSNo, TotalBillableHours, NetAvailableHours, Segment]

    JOIN RULES:
    Match pnl_data.FinalCustomerName = ut_data.FinalCustomerName 
    AND STRFTIME(pnl_data.Month, '%Y-%m') = STRFTIME(ut_data.Date, '%Y-%m')

    OUTPUT: [Dimension, Numerator, Denominator, Final_Result]
    """
    
    response = llm.invoke(system_prompt + f"\nUser Query: {user_query}")
    sql = response.content.strip().replace("```sql", "").replace("```", "")
    
    try:
        df = conn.execute(sql).df()
        return "DATA", sql, df
    except Exception as e:
        return "ERROR", sql, str(e)

# --- 3. UI (With Improved Insights) ---
st.title("🏛️ L&T Executive Analyst v13.0")
user_input = st.text_input("How can I assist you with P&L or UT data?")

if user_input:
    mode, sql, result = execute_ai_query(user_input)
    
    if mode == "CHAT":
        st.write(result)
    elif mode == "DATA":
        if not result.empty:
            # 2-Point Insights with Formatting
            avg_val = result.iloc[:,-1].mean()
            peak_val = result.iloc[:,-1].max()
            st.info(f"💡 **Insights:** Average is **{avg_val:,.2f}** | Peak is **{peak_val:,.2f}**")
            
        tab1, tab2 = st.tabs(["📊 Dashboard", "🧾 Calculation Details"])
        with tab1:
            # Main result display
            st.dataframe(result.iloc[:, [0, -1]])
            if len(result) > 1:
                fig, ax = plt.subplots(figsize=(10, 3))
                ax.plot(result.iloc[:, 0].astype(str), result.iloc[:, -1], marker='o', color='#00529B')
                plt.xticks(rotation=45)
                st.pyplot(fig)
        with tab2:
            st.markdown("### 🔍 Calculation Audit")
            st.write("SQL generated by AI:")
            st.code(sql, language="sql")
            st.write("Full breakdown (Numerator vs Denominator):")
            st.dataframe(result)
    elif mode == "ERROR":
        st.error(f"Something went wrong: {result}")
